language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t denyslins/react_project -f ./react_project/frontend/Dockerfile.dev ./react_project/frontend

script:
  - docker run -e CI=true denyslins/react_project npm run test -- --coverage
