apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  container:
    - name: client
      image: denyslins/udemy-react-multi-client
      ports:
        - containerPort: 3000
