version: '3'
services:
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
