version: "3"
services:
  redis:
    image: "redis"
  web:
    depends_on:
      - redis
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
