version: '3'
services:
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app
    command: ["npm", "run", "test"]

