FROM node:alpine as builder

WORKDIR /usr/app

COPY ./frontend/package.json ./

RUN npm install

COPY ./frontend ./

RUN npm run build

FROM nginx:alpine

COPY --from=builder /usr/app/build /usr/share/nginx/html
